import React , {useEffect} from 'react'
import { auth } from '../Helpers/Firebase';
import Header from '../Helpers/Header';
import './Resources.css';
import { useNavigate, useParams } from "react-router-dom";

function Resources() {
    const navigate = useNavigate();

const tapped = () => {
    var coll = document.getElementsByClassName("collapsible");
    var i;
    
    for (i = 0; i < coll.length; i++) {
      coll[i].addEventListener("click", function() {
        this.classList.toggle("active");
        var content = this.nextElementSibling;
        if (content.style.maxHeight){
          content.style.maxHeight = null;
        } else {
          content.style.maxHeight = content.scrollHeight + "px";
        } 
      });
    }
}

useEffect(() => {
    auth.onAuthStateChanged((user) => {
        if (user) {
        } else {
            navigate('/');
        }
      });
}, [])

    return (
        <div className='resources'>
            <Header />
            <div class="ratios">
                <div class="eachratio" onClick={tapped}>
                    <h3 class="collapsible" >SORTINO RATIO</h3>
                    <div class="content">
                    <h4>How to Calculate</h4>
                    <h5>The difference between portfolio return and risk free rate divided by the standard deviation of negative
                        returns</h5>
                    <h5>NOTE : Calculated as per monthly data of three years</h5>
                    <br />
                    <h4>IMPORTANCE</h4>
                    <ul>
                        <li>A measure of the risk adjusted performance it indicates the excess returns generated by an investments for
                            its downside risk.</li>
                            <li>It uses downside deviation from means as its risk measure and not total deviation .</li>
                            <li>A higher sortino ratio relative it its peers reflects better risk-adjusted performance.</li>
                    </ul>
                    <h5>Minimum:- 7</h5>
                    <h5>Maximum :- 19</h5>
                    </div>
                </div>

                <div class="eachratio" onClick={tapped}>
                    <h3 class="collapsible">EXPENSE RATIO</h3>
                    <div class="content">
                    <h4>How to Calculate</h4>
                    <h5>Operation Expense divided by average value of fund assets </h5>
                    <br />
                    <h4>IMPORTANCE</h4>
                    <ul>
                        <li>It indicates how much the fund charges its investors for managing their money .</li>
                            <li>A higher ratio indicates that more expences are incurred to manage a set amount of assets.</li>
                            <li>A lower ratio indiacates that less are expences are needed to measure the same amount of assets.</li>
                            <li>If somebody invests directly in mutual fund it means not through distributors then they can save approx 1%  in the expences  ratio ,however ,for investing directly one should have proper knowledge of categories with risk and return which is better understand with the help of mutual fund distributors.</li>
                    </ul>
                </div>
                </div>

        <div class="eachratio" onClick={tapped}>
            <h3 class="collapsible">TURNOVER %</h3>
            <div class="content">
            <h4>How to Calculate</h4>
            <h5>(Minimum No of securities bought or sold divided by average net assets ) multiplied by 100% </h5>
            <br />
            <h4>IMPORTANCE</h4>
            <ul>
                <li>It indiacates the frequency at which a funds holding are bought and sold.</li>
                    <li>A low turnover ratio is desirable over a high turnover ratio .</li>
                    <li>A portfolio turnover ratio is considered low when the ratio is 30% or lower. When the turnover ratio is low it indicates that the fund manager is following a buy and hold investments strategy .</li>
                    <li>All else equal , a portfolio with a higher turnover ratio will be incurring more expenses than a fund with a lower turnover ratio . Funds with low Turnover ratio are called passively managed funds</li>
                    <li>Funds with a high turnover ratio indicates a considerable amount of buying and selling of securities ( a fast- paced investments strategy ) .Funds with a high turnover ratio are called actively managed funds </li>
                    <li>A high turnover ratio is justified if the fund managers is able to generate comparatively higher returns ( on a risk- adjusted basis) than a similar-style fund with a low turnover ratio.</li>
            </ul>
        </div>
        </div>

        <div class="eachratio" onClick={tapped}>
            <h3 class="collapsible">ALPHA</h3>
            <div class="content">
            <h4>How to Calculate</h4>
            <h5>Fund performance – Benchmark Performance </h5>
            <br />
            <h4>IMPORTANCE</h4>
            <ul>
                <li>Measures of performance of an investments as compared to a suitable index , such as nifty Index </li>
                    <li>Positive alpha means that the portfolio has performed better than the benchmark index</li>
                    <li>A negative alpha reflects an investments that is underperforming as compared to the benchmark index </li>
                 
            </ul>
            <h5>NOTE : Calculated as per data of three years.</h5>
            <h5>Minimum:- 45</h5>
            <h5>Maximum :- 12</h5>
            </div>

        </div>


        <div class="eachratio" onClick={tapped}>
            <h3 class="collapsible">R-SQUARED</h3>
            <div class="content">
            <h4>IMPORTANCE</h4>
            <ul>
                <li>R –squared is generally interpreted as the percentage od a fund or security‘s movements that can be explained by movements in a benchmark index. </li>
                    <li>R-squared of 80% means that the fund follows the benchmark index movements by 80%</li>
                  
                 
            </ul>
            <h5>NOTE : Calculated as per monthly date of three years.</h5>
            <h5>Minimum:- 0</h5>
            <h5>Maximum :- 1</h5>
        </div>
        </div>


        <div class="eachratio" onClick={tapped}>
            <h3 class="collapsible">PB RATIO</h3>
            <div class="content">
            <h4>How to Calculate</h4>
            <h5>Average Of PB Ratio </h5>
            <h5>NOTE : Calculation – total market capitalization divided by total shareholder’s Fund.</h5>

            <br />
            <h4>IMPORTANCE</h4>
            <ul>
                <li>A Low ratio indicates that the stock is undervalued and a higher ratio indicates the stock is overvalued </li>
                
                 
            </ul>
            <h5>Minimum:- 0</h5>
            <h5>Maximum :- 7</h5>
        </div>
        </div>


        <div class="eachratio" onClick={tapped}>
            <h3 class="collapsible">PE RATIO</h3>
            <div class="content">
            <h4>How to Calculate</h4>
            <h5>Average Of PE Ratio </h5>
            <h5>NOTE : Calculation – total market capitalization divided by annual net </h5>

            <br />
            <h4>IMPORTANCE</h4>
            <ul>
                <li>At a glance an investor can view price of the company when it will be at a multiple of 15PE . Value analyst prefer companies at or below 15 PE multiple . </li>
                
                 
            </ul>
            <h5>Minimum:- 0</h5>
            <h5>Maximum :- 104</h5>
        </div>
        </div>


        <div class="eachratio" onClick={tapped}>
            <h3 class="collapsible">SHARPE RATIO</h3>
            <div class="content">
            <h4>How to Calculate</h4>
            <h5>Difference between the portfolio returns and risk free return, divided by the standard deviation of the portfolio . </h5>
            <h5>NOTE : Calculated as per monthly data of three years  </h5>

            <br />
            <h4>IMPORTANCE</h4>
            <ul>
                <li>The sharpe ratio assesses the returns generated by a portfolio against each of risk undertaken . </li>
                <li>The higher the sharpe  ratio , the better ,since a high sharpe ratio represents a higher returns generated per units of risk .</li>
                <li>It must only be used as a comparative tool to evaluate the performance of a number of portfolio of funds .</li>
                <li>A sharpe Ratio will invariably tell you which of the portfolios under comparison is performing to the best of its abilities .</li>
                
                 
            </ul>
            <h5>Minimum:- 2</h5>
            <h5>Maximum :- 5</h5>
        </div>
        </div>

        <div class="eachratio" onClick={tapped}>
            <h3 class="collapsible">Standard Deviation</h3>
            <div class="content">
            <h4>How to Calculate</h4>
            <ul>
                <li>Step 1 : Find the means </li>
                <li>Step 2 : For each data point ,find the square of its distance to the mean.</li>
                <li>STEP 3 : Sum the values from step 2</li>
                <li>Step  4 : Divide by the number of data points</li>
                
                 
            </ul>
            <h5>NOTE : Calculated as per monthly data of three years  </h5>

            <br />
            <h4>IMPORTANCE</h4>
            <ul>
                <li>The standard deviation is the risk factor of the portfolio and its indicative of the volatility of the fund . </li>
                <li>The higher the standard deviation the higher the volatility of the fund which means the mutual funds performance , fluctuated high above the average but also significantly below it .</li>
                <li>A lower standard deviation implies little fluctuation in returns .</li>
       
                
                 
            </ul>
            <h5>Minimum:- 0</h5>
            <h5>Maximum :- 43</h5>
        </div>
        </div>


        <div class="eachratio" onClick={tapped}>
            <h3 class="collapsible">Net Assets  ( CR )</h3>
            <div class="content">
            <h4>What is Net Assets ?</h4>
            <h5>Methods of calculating assets under managements vary among companies Total firm assets under managements will increase or when new customers and new assets are acquired . Factors causing decrease in AUM include decreases in market value from investments performance losers fund closures and clients redemptions .since the value of most financial assets changes on a daily basis the AUM for an investment manager also changes daily  </h5>

            <br />
            <h4>EXAMPLE</h4>
            <h5>HDFC has the highest AUM in equity and debt category as of sep 19 being over 80000 cr and 180000 cr respectively </h5>
            <h4>NOTE</h4>
            <h5>The more assets under management the better it is for debt funds .however this should not be the only deciding factor for equity funds.</h5>
        </div>
        </div>


        <div class="eachratio" onClick={tapped}>
            <h3 class="collapsible">BETA</h3>
            <div class="content">
            <h4>How to Calculate</h4>
            <h5>Fund’s standard deviation of returns devided by the benchmark’s Standard deviation of returns . the resulting value is multiplied by the correlation of the security ‘s returns and the benchmark’s returns.
                 </h5>
            <h5>NOTE : Calculated as per monthly data of three years  </h5>

            <br />
            <h4>IMPORTANCE</h4>
            <ul>
                <li>A measure of fund’s sensitivity to market movements . </li>
                <li>A beta of more than 1 indicates higher volatility in the value of an investments in response to ups and downs in the value of the benchmark</li>
                <li>Beta of less than 1 indicates narrower volatility</li>
                <li>For risk averse investors who prefer a low fluctuation in prices the mutual fund with lower beta is preferable .</li>
                
                 
            </ul>
            <h5>Minimum:- 0.9</h5>
            <h5>Maximum :- 4</h5>
        </div>
        </div>
    </div>
    </div>
    )
}

export default Resources
